let Name=["samiksha","sita","sumit","sakshi","sarika","sulakshana"];
let name=["rahul","ram","rakesh","raj"];
//console.log(Name.reverse());
//console.log(Name);
//console.log(Name.reverse());
//console.log(Name.concat(name));
//console.log(name.reverse());
console.log(Name.concat(name));
console.log(name.reverse());
console.log(Name.reverse());